// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMDwPHPjDsAjuP3rbe0wTyDun4_22uJ9g',
    appId: '1:988811633989:web:16e249d645103e97ef4a2c',
    messagingSenderId: '988811633989',
    projectId: 'flip-and-flash',
    authDomain: 'flip-and-flash.firebaseapp.com',
    storageBucket: 'flip-and-flash.appspot.com',
    measurementId: 'G-0BR15DHXY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3P9ldE1vvRQdUFK7DWLK_Di3bonyV1IA',
    appId: '1:988811633989:android:de5c551cb764bec2ef4a2c',
    messagingSenderId: '988811633989',
    projectId: 'flip-and-flash',
    storageBucket: 'flip-and-flash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_euMfE96lHXUe-9ARRA_L4hsFcQSIi6g',
    appId: '1:988811633989:ios:e020622ee1c0c4f5ef4a2c',
    messagingSenderId: '988811633989',
    projectId: 'flip-and-flash',
    storageBucket: 'flip-and-flash.appspot.com',
    iosClientId: '988811633989-4e2j4hel1prkl63naa71g33e7e0cgv05.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipAndFlash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_euMfE96lHXUe-9ARRA_L4hsFcQSIi6g',
    appId: '1:988811633989:ios:e9154a8a755c5192ef4a2c',
    messagingSenderId: '988811633989',
    projectId: 'flip-and-flash',
    storageBucket: 'flip-and-flash.appspot.com',
    iosClientId: '988811633989-l6e2igo3vfbltrg4rf0a6gnvk4ijn4to.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipAndFlash.RunnerTests',
  );
}
